name: RoflSigns
version: 1.4.4
description: Allows roflcopterss99 to place signs anywhere.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-roflsigns/
main: com.moltendorf.bukkit.roflsigns.Plugin
